### ISSUE TITLE
Invalid gene loss rate

### ISSUE THREAD

**Issue by BenoitMorel** [adamallo/SimPhy#9]
Hi Adamallo,

Thanks a lot for your great simulator!

I have a question regarding the loss and duplication rates: you forbid the loss rate to be lower than the duplication rate (https://github.com/adamallo/SimPhy/blob/master/src/main.c#L3637)

Is it because it would almost certainly imply that all gene lineages would go extinct?
What if I also add transfers? (for instance, if I want no gene duplication, but gene transfer and loss)

Benoit

**Comment by adamallo** [comment]
The current version of SimPhy only implements horizontal gene transfer/lateral gene transfer that replaces a pre-existing gene copy (locus tree branch). Therefore, the transfer rate does not modify the expected number of locus-tree leaves.

In any case, it is true that the current error forcing duplication rate to be >= loss rate is too restrictive, since it may make sense to simulate under these conditions. In fact, this issue has been reported before (see https://groups.google.com/forum/#!topic/simphy/99Yu_Failes ). I plan to relax this strict control of the input simulation parameter values in the main branch of SimPhy. In the meantime, please, try the [flexiblesim](https://github.com/adamallo/SimPhy/tree/flexiblesim) branch of the repository. This allows to relax this condition when using the argument "-f 1".

Thanks,

 DM

**Comment by BenoitMorel** [comment]
Great now everything makes sense. Thanks a lot for your explanations!
